name: Configure BubbleChat Customizer

on:
  workflow_dispatch:
    inputs:
      componentId:
        description: "Component Id"
        required: true
        default: "6884b891-ab15-4bc6-b67e-b45a233cdd5f"
      siteUrl:
        description: "SharePoint Site URL"
        required: true
        default: "https://s63fb.sharepoint.com/sites/SelfServiceAgent"
      botUrl:
        description: "Bot URL"
        required: true
        default: "https://6a0383e2ebc3ee40bdc9d05198285a.12.environment.api.powerplatform.com/powervirtualagents/botsbyschema/crfb3_selfServiceAgent/directline/token?api-version=2022-03-01-preview"
      botName:
        description: "Bot Display Name"
        required: false
        default: "Service Desk Agent"
      buttonLabel:
        description: "Button Label"
        required: false
        default: "Chat now"
      botAvatarImage:
        description: "Bot Avatar Image URL"
        required: false
        default: ""
      botAvatarInitials:
        description: "Bot Avatar Initials"
        required: false
        default: "SD"
      customScope:
        description: "Custom Scope"
        required: true
        default: "api://27eb69cb-53e6-40db-8533-dfa804dca4ac/Sites.Read"
      clientId:
        description: "Azure AD App Client ID"
        required: true
        default: "4ffd1a7a-9a30-48a9-bc3d-51060e46591b"
      authority:
        description: "Authority URL"
        required: true
        default: "https://login.microsoftonline.com/s63fb.onmicrosoft.com"

permissions:
  id-token: write
  contents: write

jobs:
  configure:
    name: Configure Bubble Chat
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: M365 login
        id: login
        uses: pnp/action-cli-login@v3
        with:
          TENANT: ${{ secrets.TENANT }}
          APP_ID: ${{ secrets.APP_ID }}

      - name: Set BubbleChat Customizer Properties
        run: |
          m365 spo customaction set \
            --id "${{ github.event.inputs.componentId }}" \
            --webUrl "${{ github.event.inputs.siteUrl }}" \
            --name "BubbleChatCustomizer" \
            --scope Site \
            --clientSideComponentProperties "{
              \"botURL\": \"${{ github.event.inputs.botUrl }}\",
              \"botName\": \"${{ github.event.inputs.botName }}\",
              \"buttonLabel\": \"${{ github.event.inputs.buttonLabel }}\",
              \"botAvatarImage\": \"${{ github.event.inputs.botAvatarImage }}\",
              \"botAvatarInitials\": \"${{ github.event.inputs.botAvatarInitials }}\",
              \"customScope\": \"${{ github.event.inputs.customScope }}\",
              \"clientID\": \"${{ github.event.inputs.clientId }}\",
              \"authority\": \"${{ github.event.inputs.authority }}\"
            }"
        shell: bash
