name: Deploy BubbleChat Customizer

on:
  workflow_dispatch:
    inputs:
      siteUrl:
        description: "SharePoint Site URL"
        required: true
        default: "https://s63fb.sharepoint.com/sites/SelfServiceAgent"
      clientId:
        description: "Azure AD App Client ID"
        required: true
        default: "4ffd1a7a-9a30-48a9-bc3d-51060e46591b"
      tenant:
        description: "Tenant ID"
        required: true
        default: "582af8b1-0ad0-4519-bae9-067c35c065c2"
      botUrl:
        description: "Bot URL"
        required: true
        default: "https://6a0383e2ebc3ee40bdc9d05198285a.12.environment.api.powerplatform.com/powervirtualagents/botsbyschema/crfb3_selfServiceAgent/directline/token?api-version=2022-03-01-preview"
      customScope:
        description: "Custom Scope"
        required: true
        default: "api://27eb69cb-53e6-40db-8533-dfa804dca4ac/Sites.Read"
      authority:
        description: "Authority URL"
        required: true
        default: "https://login.microsoftonline.com/s63fb.onmicrosoft.com"
      botName:
        description: "Bot Display Name"
        required: false
        default: "Service Desk Agent"
      buttonLabel:
        description: "Button Label"
        required: false
        default: "Chat now"
      botAvatarImage:
        description: "Bot Avatar Image URL"
        required: false
        default: ""
      botAvatarInitials:
        description: "Bot Avatar Initials"
        required: false
        default: "SD"

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install PnP PowerShell
        run: |
          Install-Module -Name PnP.PowerShell -Force -Scope CurrentUser
        shell: pwsh

      - name: Run BubbleChat Customizer Script
        run: |
          .\BubbleChatPnPCustomAction.ps1 `
            -siteUrl "${{ github.event.inputs.siteUrl }}" `
            -clientId "${{ github.event.inputs.clientId }}" `
            -tenant "${{ github.event.inputs.tenant }}" `
            -botUrl "${{ github.event.inputs.botUrl }}" `
            -customScope "${{ github.event.inputs.customScope }}" `
            -authority "${{ github.event.inputs.authority }}" `
            --certificateBase64Encoded "${{ secrets.CERTIFICATE_ENCODED }}" `
            -certificatePassword "${{ secrets.CERTIFICATE_PASSWORD }}" `
            -botName "${{ github.event.inputs.botName }}" `
            -buttonLabel "${{ github.event.inputs.buttonLabel }}" `
            -botAvatarImage "${{ github.event.inputs.botAvatarImage }}" `
            -botAvatarInitials "${{ github.event.inputs.botAvatarInitials }}"
        shell: pwsh
