name: "Deploy SSPKG"

on:
  # push:
  #   branches:
  #     - "main"
  #     - "feat/ci"
  workflow_dispatch:
    inputs:
      appId:
        description: "The id from the package-solution.json"
        required: true
        default: "105f66d9-0260-4c5d-819c-fb7e70a9b213"

env:
  PACKAGE: "it-self-service2.sppkg"
  APP_CATALOG: "https://s63fb.sharepoint.com/sites/appcatalog"

permissions:
  id-token: write
  contents: write

jobs:
  spfx-gulp:
    name: "SPPKG Deployment"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node.js install
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: NPM install
        run: npm ci

      - name: Gulp install
        run: npm i -g gulp

      - name: Gulp package
        run: |
          gulp bundle --ship
          gulp package-solution --ship

      - name: M365 login
        id: login
        uses: pnp/action-cli-login@v3
        with:
          TENANT: ${{ secrets.TENANT }}
          APP_ID: ${{ secrets.APP_ID }}
          # ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          # ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          # CERTIFICATE_ENCODED: ${{ secrets.CERTIFICATE_ENCODED }}
          # CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}

      - name: Check custom action list
        run: |
          m365 spo customaction list --webUrl "https://s69fb.sharepoint.com/sites/SelfServiceAgent"
        shell: bash

      - name: Register the app in the App Catalog
        run: |
          m365 spo app add \
            --filePath sharepoint/solution/${{ env.PACKAGE }} \
            --overwrite \
            --appCatalogUrl "${{ env.APP_CATALOG }}" \
            --output json
        shell: bash

      - name: Deploy app
        run: |
          m365 spo app deploy \
            --id ${{ github.event.inputs.appId }} \
            --appCatalogUrl "${{ env.APP_CATALOG }}" \
            --skipFeatureDeployment
        shell: bash
