name: "Deploy SSPKG"
on:
  workflow_dispatch:
    inputs:
      appId:
        description: "The id from the package-solution.json"
        required: true
        default: "105f66d9-0260-4c5d-819c-fb7e70a9b213"
      componentId:
        description: "ComponentId of the BubbleChat"
        required: true
        default: "6884b891-ab15-4bc6-b67e-b45a233cdd5f"
      siteUrl:
        description: "SharePoint Site URL"
        required: true
        default: "https://s63fb.sharepoint.com/sites/SelfServiceAgent"
      botUrl:
        description: "Bot URL"
        required: true
        default: "https://6a0383e2ebc3ee40bdc9d05198285a.12.environment.api.powerplatform.com/powervirtualagents/botsbyschema/crfb3_selfServiceAgent/directline/token?api-version=2022-03-01-preview"
      botName:
        description: "Bot Display Name"
        required: false
        default: "Service Desk Agent"
      customScope:
        description: "Custom Scope"
        required: true
        default: "api://27eb69cb-53e6-40db-8533-dfa804dca4ac/Sites.Read"
      clientId:
        description: "Azure AD App Client ID"
        required: true
        default: "4ffd1a7a-9a30-48a9-bc3d-51060e46591b"
      authority:
        description: "Authority URL"
        required: true
        default: "https://login.microsoftonline.com/s63fb.onmicrosoft.com"

env:
  PACKAGE: "it-self-service2.sppkg"
  APP_CATALOG: "https://s63fb.sharepoint.com/sites/appcatalog"

permissions:
  id-token: write
  contents: write

jobs:
  spfx-gulp:
    name: "SPPKG Deployment"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node.js install
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: NPM install
        run: npm ci

      - name: Gulp install
        run: npm i -g gulp

      - name: Gulp package
        run: |
          gulp bundle --ship
          gulp package-solution --ship

      - name: M365 login
        id: login
        uses: pnp/action-cli-login@v3
        with:
          TENANT: ${{ secrets.TENANT }}
          APP_ID: ${{ secrets.APP_ID }}
          # ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          # ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          # CERTIFICATE_ENCODED: ${{ secrets.CERTIFICATE_ENCODED }}
          # CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}

      - name: Upload, Deploy to App Catalog and install in the site
        run: |
          APP_ID="${{ github.event.inputs.appId }}"
          SITE_URL="${{ github.event.inputs.siteUrl }}"
          APP_CATALOG="${{ env.APP_CATALOG }}"
          PACKAGE="${{ env.PACKAGE }}"

          EXISTS=$(m365 spo app list \
            --appCatalogScope tenant \
            --appCatalogUrl "$APP_CATALOG" \
            --output json | jq -r --arg id "$APP_ID" '.[] | select(.ProductId==$id) | .ProductId')

          NEEDS_INSTALLATION=0
          if [[ -z "$EXISTS" ]]; then
            NEEDS_INSTALLATION=1
          fi

          m365 spo app add \
            --filePath "sharepoint/solution/$PACKAGE" \
            --appCatalogUrl "$APP_CATALOG" \
            --overwrite

          m365 spo app deploy \
            --id ${{ github.event.inputs.appId }} \
            --appCatalogUrl "${{ env.APP_CATALOG }}" \

          if [ "$NEEDS_INSTALLATION" -eq 1 ]; then
            echo "Installing app for the first time..."
            m365 spo app install --siteUrl "$SITE_URL" --id "$APP_ID"
          fi
        shell: bash

      - name: Register custom action
        run: |
          SITE_URL=${{ github.event.inputs.siteUrl }}
          EXISTING_ID=$(m365 spo customaction list --webUrl "$SITE_URL" --output json | jq -r '.[] | select(.Name=="BubbleChatCustomizer") | .Id')

          if [ "$EXISTING_ID" != "" ]; then
            echo "Removing existing BubbleChat custom action with ID: $EXISTING_ID"
            m365 spo customaction remove --webUrl "$SITE_URL" --id $EXISTING_ID --force
          fi

          m365 spo customaction add \
            --webUrl "$SITE_URL" \
            --name "BubbleChatCustomizer" \
            --title "BubbleChat" \
            --scope "Web" \
            --location "ClientSideExtension.ApplicationCustomizer" \
            --clientSideComponentId "${{ github.event.inputs.componentId }}" \
            --clientSideComponentProperties "{
              \"botURL\": \"${{ github.event.inputs.botUrl }}\",
              \"botName\": \"${{ github.event.inputs.botName }}\",
              \"buttonLabel\": \"Chat Now\",
              \"botAvatarInitials\": \"SD\",
              \"customScope\": \"${{ github.event.inputs.customScope }}\",
              \"clientID\": \"${{ github.event.inputs.clientId }}\",
              \"authority\": \"${{ github.event.inputs.authority }}\"
            }"
        shell: bash
